version: "3"
services:
  db:
    image: postgres:latest
    container_name: aws-serverless-ecom # Name can be anything
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/ # Path to the SQL script to initialize the DB

  app:
    build: .
    container_name: my-python-container # Name can be anything
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db-data:
